trigger: none

pr: none

pool:
  vmImage: ubuntu-latest

stages:

# =========================
# Stage: Terraform Plan
# =========================
- stage: Plan
  displayName: Terraform Plan Stage
  jobs:
  - job: TerraformPlan
    displayName: Plan Job
    steps:

    # Terraform Install
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    # Terraform Init
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/prod'
        commandOptions: '-reconfigure'
        backendServiceArm: 'nitesh-sc'
        backendAzureRmStorageAccountName: 'stgnitesh2'
        backendAzureRmContainerName: 'niteshcontainer'
        backendAzureRmKey: 'tf.tfstate'

    # Terraform Plan
    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/prod'
        environmentServiceNameAzureRM: 'nitesh-sc'


# =========================
# Stage: Terraform Apply
# =========================
- stage: Apply
  displayName: Terraform Apply Stage
  dependsOn: Plan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: TerraformApply
    displayName: Apply Job
    steps:

    # Terraform Install
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    # Terraform Init
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/prod'
        commandOptions: '-reconfigure'
        backendServiceArm: 'nitesh-sc'
        backendAzureRmStorageAccountName: 'stgnitesh2'
        backendAzureRmContainerName: 'niteshcontainer'
        backendAzureRmKey: 'tf.tfstate'

    # Terraform Apply
    - task: TerraformTask@5
      displayName: Terraform Apply
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/env/prod'
        commandOptions: '-auto-approve'
        environmentServiceNameAzureRM: 'nitesh-sc'
